# THRIVING OFF OF TENSIONS: {#paper0}     
**A PARADOX PERSPECTIVE ON CREATIVE ENTREPRENEURSHIP**    
  
>> **Abstract.** This conceptual paper introduces paradox theory as a lense for creative industries research. We first trace the theoretical developments over the last century explaining the origings of the seemingly irreconcilable conflict between creativity and commerce. We then argue that much of the assumptions are untenable in the contemporary creative industries context, as the field cannot be seen as the hereditary of the same features as arts worlds. We introduce the paradox lens as an  alternative theoretical framework and discusses the implications of such an approach to the broader creative industries research in management, cultural sociology, human geography, and related disciplines that have focused extensively on studying creative industries. 

**Keywords:** Creative industries; Paradox theory; 

## Introduction and Lit review notes   
>> The test of a first-rate intelligence is the ability to hold two opposed ideas in mind at the same time and still retain the ability to function. (F. Scott Fitzgerald)   

Human creativity is increasingly seen as a key resource for innovation, entrepreneurial success, sustained competitive advantage, economic growth, and complex societal problem-solving [@Hartley2005]. This growing importance of creativity has drawn considerable research attention to the creative industries - the individuals and organizations using creativity as the main resource of production [Ref]. As a setting it has been extensively studied both being an object of inquiry in itself, as well as an exemplary field for understanding the organization of creativity and thus the anticipated developments in other settings. The questions that are explored in the setting are very diverse, and have helped to shed light on xxxx xxxx. 

However, also a notable limitation can be identified. Most of the theories that the creative industries research relies on theories the . * As implied in the title of the nominal work on the economic aspects of creative industries by Richard Caves - contracts between arts and commerce - creative industries and the entrepreneurship within is a hybrid, a compromise of creative endeavours and doing business. The key defining principle of CI is thus the conflict. This is also the premise of the field of workings. INterpreted, according to the same tradition as in arts, as creating dual structure within the sector - at market level - niche. Individuals, creative non creative that are diverse, and difficult to collaborate, at strategic level, at sociological level - capitals. 
  

Intro: Why would one research creative industries? 
Politically, the creative industries setting has been interesting since it has been included in specific neo-liberal political agendas at city and government levels, for economic, cultural and social policy targets. 
Economically, higher value added, innovation. 
From an organizational perspective, it is seen as a future-forward setting, a forerunner of new forms of labour organization and entrepreneurial activity. 
Sociologically, 

Creative industries - a definition and the development of the concept linked to art

Art versus money: Why we mostly think so? 
From the book of Bilton - that even in the arts world the notion is rather new against the backdrop of the whole art's history, and only exists since the romantic victorian period. Before artists didn't have that much problem with money-making (Claartje's thesis). 

The paradox perspective
The prevelance of persistent tensions that are seemingly irreconsilable is not neccessarily exclusive to the creative and artistic settings. More recently, in response to the need to manage such tensions the paradox perspective has emerged. 
  

Many existent studies on creative industries suggest that these problems arise due to the conflict between creative and financial goals pursued (Townley et al., 2009, REF). Translating the romantic art versus commerce conflict to creative industries, the authors argue that the cultural (or artistic, creative) fields and economic fields are distinct from each other and have different sets of rules, logics and reward systems (Bourdieu, 1993). As Hesmondhalgh (2006) explains, marketing (i.e. commercialization) and increased scale in cultural production (i.e. increasing the economic profit) comes at the expense of lower levels of symbolic capital and loss of autonomy, and vice versa. 

What is you gap/ RQ? 
* However, how we commonly understand the field is largely based on the huge body of work that existed before the 2000s on the economic and sociological aspects of the cultural production and  consumptions in the arts and cultural industries. 
* This view is adopted from previous work on more traditional arts fields. And creative industries are seen as a new extension of this field. 
* Many have argued that this clear distinction is untenable. That in fact, creative and commercial considerations, aspects are intertwined etc. jacobs - double success criterion. 
However, not much work exists beyond stating this fact. How do 

For a long time, the art versus commerce conflict has been examined from a trade-off perspective, implying that the conflicts can be resolved by choosing between the two poles. Most normative statements conclude that cultural values should be privileged opposed to economic ones (Slater & Tonkiss, 2001). However, as argued by Jacobs more recently (2012; 2013), firms in creative industries, as opposed to arts organizations, face a double success criterion. Instead of choosing, they have to simultaneously build up reputation for being creative in order to become financially successful, and work on commercialization in order to be able to produce creative work. Hence, the creative industries tensions are more paradoxical, rather than trade-offs, as both creative and financial success are needed, but each goals require fundamentally different, at times even mutually exclusive decisions, resources and structures.
According to the scholarship in the field of paradox theory, many of the tensions and complex demands in in contemporary entrepreneurship are in fact paradoxes ??? ???contradictory yet interrelated elements of organization that seem logical in isolation but inconsistent and oppositional in conjunction and yet persist over time??? (Jarzabkowski et al., 2013, p.245). According to paradox scholars, successful organizations apply a "both/and" approach to these tensions - instead of choosing between A and B, they seek to find a balance between both demands (Lewis & Smith, 2014; Shad et al., 2016). However, accommodating of paradoxes in organization is a challenging task and requires specific types of practices and decisions.


What do you do to address this gap? 

We believe that paradox theory can shed light on these questions. In this article, we suggest that the conflict between creativity and commerce in creative industries is better seen as a paradox??? 
This is a conceptual paper that applies insights from paradox theory to provide an improved understanding of the tensions identified in prior literature, and their implications for creative industries research and practice. 
The conceptual supported by empirical illustrations from a research study conducted in order to understand the interplay between business and creative orientations in the creative industries. 

So what? 
This provides researchers in many domains interested in studying creative industries a new perspective to frame their questions + practitioners the opportunity to reframe their problems and find tools for coping with them, previously thought of not being possible. 



## Creativity versus commerce: What the literature says?   
  
The clash between the creative expression and the business success, efficiency and "managerialism" has been discussed extensively in arts management (Chaston, 2008; Hirschman, 1983), cultural sociology (Negus, 1995) and cultural economics (Caves, 2000, Caves (2003); Holbrook and Addis, 2008). More recently the discussion has also appeared in entered the realm of entrepreneurship research (DeFillippi et al., 2007; Jones et al., 2015; Lampel et al., 2000; Townley et al., 2009). The assumptions on the divide between creativity and commerce in creative industries are inspired by two main contributions - the notion of the Culture Industry introduced by Theodor Adorno and Max Horkheimer in the chapter "The Culture Industry: Enlightenment as Mass Deception" of the book Dialectic of Enlightenment (1946; 1972), and the Theory of Fields put forward by Pierre Bourdieu (Bourdieu and Johnson, 1993; O???connor, 2010; Townley and Beech, 2010).
Adorno and Horkheimer coined the term Culture Industry to designate the factory-like production of cultural commodities. According to their ideas, "under monopoly capitalism, art and culture had [now] become thoroughly absorbed by the economy" (O???connor, 2010, p. 11). For them the Culture Industry united the worst of both worlds - popular culture and high art. It used the new mass reproduction and distribution opportunities to circulate cultural goods resembling art but deprived from the meaning and depth, aimed to control the masses (Horkheimer and Adorno, 1972, 1946; O???connor, 2010).
These ideas were further advanced in Bourdieu's Theory of Fields. According to Bourdieu (1993; 1992) the economic power field (and hence the economic production and consumption) and the field of cultural production are two distinct fields, with different agents, sets of rules, logics and reward systems, according to which different types of capitals are generated and exchanged. As Scott explains, "for Bourdieu, capitals are unevenly distributed relational assets of accumulated power resources endowing actors with field-circumscribed agency." (2012, p.244, referring to Bourdiue, 1997, p.46). The Economic Field is characterized by high levels of economic capital but low levels of cultural capital (knowledge) and symbolic capital (prestige and reputation), and the opposite holds true for the Cultural Field. While all forms of capital can be mobilised and converted, the possesion of these power resources gives different advantages depending on the field and its rules (Scott, 2012).
For Bourdieu, the large-scale cultural production, which would include creative industries, is a somewhat corrupt subfield of the Cultural Field. Agents use and produce both economic and cultural capitals, but because of the interaction with economic field, it comes at the loss of autonomy and symbolic capital, which to the author is the most important type of capital for creative production (Bourdieu and Johnson, 1993; Hesmondhalgh, 2006). It follows from this argument that the true, autonomous cultural production can only be small-scale and independent of the field of power and economy (Hesmondhalgh, 2006). Consequently, when used for theorteticizing about the management of cultural production, these ideas have developed into a trade-off perspective where pure creative and commercial creative production are often seen as irreconcilable.
Scholars have explored this opposition across multiple levels. At the industry levels, theories divide markets into mass (commercial) and niche (artistic), and propound that different kind of creative production takes place in each of them. At the organizational and decision-making levels, the available strategic choices are equally seen as a trade-off, or an "or/if" approach. Similarly to the work developed on the generic strategies of competitive advantage (Porter, 1985), where firms are thought to compete based on either quality and reputation or on cost efficiency, in the creative setting firms would have to choose between a commercial or creative-artistic strategy. These are seen as mutually exclusive and no hybrid combinations are advisable or possible, since they have contradictory aims and use different resources and target separate markets (Canavan et al., 2013, better references).
However, many authors argue that such a clear distinction is untenable, as it ignores the realities of the most part of creative and cultural production, which actually takes place somewhere in between the two poles (Hesmondhalgh, 2006; O???connor, 2010). The Theory of Fields might be applicable to explain the arising tensions, however it would be more realistic to view both domains of activity as symbiotic and interrelated (Ilozor et al., 2006; Nation Strategic Working Group, 2000). This view is increasingly accepted in the recent creative industries' management literature. While pursuing creative and commercial ends simultaneously creates certain tensions, the co-existence of conflicting demands is seen as an organizational feature that cannot be changed and has to be accepted and managed (Bilton, 2007; DeFillippi, 2015; Lampel et al., 2000; Townley et al., 2009). Such competing strategic goals can be framed as paradoxical (Smith, 2014; Smith and Lewis, 2011), and resemble other similar competing goals, e.g. social mission and profit, or exploration and exploitation. This alternative framework has further implications for managing and organizing.


## Creativity and commerce as a paradox: Empirical support  

Across all cases the founders and managers experienced tensions arising from the clash between creativity- and business-oriented goals. The tensions came about as a result of both conflicting internal motivations, as well as competing external preassures. Despite the different drivers, we were able to identify all three commonly distinguished features of a paradox - conflict (opposition), interdependence and persistance over time. 

### Conflict and opposition
The conflict between creativity and business related goals was acknowledged in all cases. However, the nature and experiences of the opposition differed slightly across the sample, depending on the motivation to engage in creative entrepreneurship and the importance attached to certain aspects of both strategic intents. Some leaders showed a stronger urge for expression and pursuing personal goals and felt that it contrasted with what was required in order to survive in the business. Others were more prone to achieve external recognition and create impact, whether it was boundary spanning innovation or social impact, which then conflicted with the constraints imposed by clients or again the entrepreneurial realities. The resulting salient tensions pervaded several organizational issues - identity perception, decision-making, resource requirements, valuation and transaction models, work preferences, as well as employee retention and engagement.  
  
As documented in prior studies on creative entrepreneurship (Gotsi et al., 2010), the opposition and conflict often arises as individuals are forced to enact two opposing identities at the same time - that of a creator and that of a businessman. As explained by one of the managers interviewed, this conflict equally prevails at the level of organization:
"[...] in fact, if you look at the advertising [field], the commerce and creation naturally lie close to each other. You're being hired as a creative firm to give creative advise about something that they cannot do themselves. So on creativity. In between you have to listen to them as a service provider. Ultimately you have to keep your client satisfied and that is a terrible scene of tension."(Case 6)
We further found that this opposition equally permeates the perceptions as to what exactly is the content of economic transaction between the firm and the client and how it can be valued. A recurring conclusion in our conversations was that producing creative outcomes is time-consuming and unpredictable. This makes trying to put a price tag on it difficult, as it is not easy to explain exactly what the clients are paying for. As a result, prioritizing quality over efficiency, firms often invest more hours than they can bill, reducing the overall financial stability of the company; or, compromising quality, risk loosing clients in the future. A co-founder of one agency gives the following comparison:
"I guess in the end design agencies have similar issues, which is in the end selling creativity. It's something that is very difficult. I mean, selling. it's very hard to tell to a businessperson, OK, we need so many days for this project. OK, what are you going to do? I don't know, we might sit in the garden and look at the sky for ten hours, you know. (Case 1)
However, our interviews revealed that the greatest deal of the oppositions are rooted in the personal preferences of both leaders and employees in general. We already know from literature that satisfying and retaining talent is a key to success in business settings entirely dependant on highly skilled labour (Teece, 2003). In creative sectors, more often than in other economic settings, people enter the labour market and begin enterprises due to intrinsic motivations (Throsby, 2008; Fillis or Chaston, 2008). The internal motivations then conflict with market requirements and constraints. Their primary activity is to create, and they want to create something that contributes to the world, the type of work that is challenging, not boring and repetitive, yet useful and meaningful. There is hence a paradoxical conflict between the type of creative work that they would ideally want to engage in and the type of work that is available to them on the market and would help the business become more profitable. The head of strategy and design of a digital agency put it as follows: 'It should be a new thing, that's important for us. That it really for us, as designers, is like a puzzle but has not been solved yet. I think it's really important for us to solve puzzles because that's what we do all day.'(Case 15) Yet this type of work is not usually the one that is best paid, and these kinds of projects are few when compared to the overall demand. Even when there are projects that would be commercially very attractive, the intrinsic willingness not to work too much on the commercial side defines many of the major business choices.
This is further reflected as a clash between the criteria to favour upon decision making. Which of our assets do we choose to forefront as an organization? What are the right resources to develop? And how do we design our business to make sure we create value for the client and the enterprise, without compromising our own aspirations and reputation? The commercial director of a spatial design agency explains: 'Look, eventually I lose, if I say: this is only commercially attractive. For instance, we could have worked in Saudi Arabia. Commercially attractive, at least if they pay, but you can earn a lot of money there, if you're good. But we [as an enterprise] simply do not want to work in Saudi Arabia, you know. So I could stand on my head, that's simply not going to happen.'(Case 16)  
  
### Mutual interdependence: the double success criterion  
  
Despite the personal preferences and the perpetuous oppositions, informants repeatedly also stressed the interdependence between the creative and business outcomes. This paradoxical feature provided evidence for what we have earlier defined as the double success criterion - organizational success is defined by conflicting, yet mutually necessary and interwoven goals. It manifested in three ways.
First, the very terms that managers and founders used to describe their business revealed the interrelated aspect of the two poles and how they define each other. The founders often referred to themselves as being "creative entrepreneurs" and described their main activity as the "business of creativity" or "selling creativity".
Second, the leaders almost naturally accepted and worked through paradoxes in their daily practice. This paradoxical thinking in practice manifested the most in the way the managers define and describe the selection- and success- criteria that form the basis of their decision-making. The following quote is exemplary of the paradoxical thinking in the setting and similar quotes can be found in each of our cases: "[...] is it content-wise interesting, financially interesting and the third is: is it a new market? Is the client interesting? If you say, OK, we won't earn much with it, this theme is also not like - wow!, you know, but OK, nice. But the client is enormously interesting [...], it's a good name to have on you list, huh, so that is also one of the reasons to do that. [...] but all projects have to better score two of the three, even better if it's all three."(Case 16) As we will see in the next section, the approach to applying criteria when making decisions will also be the distinguishing feature between different approaches to managing paradoxes through business model design.
Third, the interdependence between the poles was best revealed when foregrounding only one of the poles to discuss the possibilities of choosing only one side. One founder explains how being only creative would not lead to success in the industry: "That whole business side, I find it crucial for a creative enterprise. I always say: we differentiate with creativity, but we earn it with the project management side. We earn it with the organization of the whole business. If you let pure creativity take its course..." (Case 8) On the opposite side, the managing director from another company discussed the prospects of prioritizing only commercial goals as depriving the whole business from what it is: "Money has to be earned and you can call that "commercial". Yeah, I just find it a necessity. One has to earn money, also in creative enterprises. [...] If we concurrently will prioritize commercial gain over creation, then there will be no more beautiful projects. Then you'll be... if you make so unique things as we do, you cannot do that." (Case 11)  

### Persistence over time   
Finally, as exemplified in the previous quote, the paradoxical nature of the creative entrepreneurship it is not always necessarily about single choices but about the durability of the conflict. The way the founders and managers experience their whole entrepreneurship process can be indeed compared to a "balancing act" (Lampel et al., 2000). It implies that the conflict will reoccur if the overall pattern is unbalanced on one side or the other. The very essence of the creativity-business paradox was very nicely explained by the founder of a packaging design agency:
"The balance is never there. You're always looking for the balance. There is a very beautiful drawing of a seesaw. Do you know what a seesaw is? [...] You have to draw a bag of money here. With a dollar sign, very good. And a heart there. So you are looking for the balance. If there's too much heart in it, you're earning too little money. If you earn too much money, there's not enough heart in it."(Case 10)
This last quote illustrates the possibility of entering virtuous or vicious circles based on an unbalanced decision-making, as explained in the model of Smith and Lewis (2011). It also beautifully coincides with what Charles Handy wrote in his book The Age of Paradox as early as in 1995: "Living with paradox is like riding a seesaw. If you know how the process works, and if the person at the other end also knows, then the ride can be exhilarating. or [...] you can receive a very uncomfortable and unexpected shock." (p.48). We can gather from our recounts that not only are the leaders in our setting exposed to a paradox, but they are almost naturally paradoxically thinking and accepting of the fact that their enterprises and economic activity is embedded in and results from these opposites. However implementing paradoxical thinking in important business decisions can be more challenging than accepting the paradox. We now turn to the results that explain how this paradoxical thinking is translated when making business model choices.  

## So WHAT? 
