# COMMITMENTS TO CONFLICTING LOGICS, BUSINESS MODELS, AND PERFORMANCE: {#paper3} 
**A CONFIGURATIONAL PERSPECTIVE** ^[The earlier version of this paper was presented in 2018 EGOS colloqium.]    

>> **Abstract.** Although business models are seen as an important source for competitive advantage, very few studies adress the role of business model design in cases where firms pursue conflicting performance goals. While existing research focuses on explaining financial performance as a function of business model design, this paper relies on the conceptual model developed by @Ocasio2016 and investigates the interplay between firm commitments to conflicting logics, business model heteroegeneity, and the resulting implications for success. Our analysis is based on a survey study of 179 creative service firms (i.e., design agencies, advertisement firms, architecture firms) and explores the pathways to being both creatively and business-wise succesful. Using a combination of Principal Component Analysis and fuzzy set Qualitative Comparative Analysis, we introduce a configurational perspective to explore the interdependancies between creative and business orientations and business model choices leading to success and the absence of it. 

## Introduction
An increasing number of firms face a reality of competing demands and interests that influence their way of strategizing and organizing, and ultimately compromise their ability to sustain the organization in the long-run [@Jarzabkowski2006]. The need of organizations to accommodate competing, often even conflicting considerations has been discussed in several literatures on topics such as triple bottom-line [@Dixon2007], hybrid organizations [@Grassl2012], organizational identity [@Voss2006], paradox theory [@Fairhurst2016], institutional logics [@Besharov2014], and pluralism [@Jarzabkowski2013]. The common examples of other demands alongside profit-making include social [@Smith2013] and environmental missions [@Dixon2007], corporate social responsibility [@Wong2017], multiple stakeholder satisfaction [@Jarzabkowski2013], or creative performance, as in the case of the research setting of this study - the creative service firms [@Jacobs2013]. While a lot has been done in order to understand the emergence, responses, and mechansism of accommodation of organizational pluralism, we know less about the opportunities for strategic differentiation that it creates [@Greenwood2011; @Ocasio2016].   
  
In this paper, we rely on the conceptual model developed by @Ocasio2016 and published in Strategic Organization, where they focus particularly on the link between commitments to conflicting logics and business models, addressing one of the key questions in strategic management - heterogeneity in value creation and capture among firms. The authors discuss "how organizational choices in business models and governance strategies are shaped by field-level pluralism and experiences of complexity." (p.293) According to them, while most of literature considers business models to be solely driven by market considerations, the presence of other demands also influences the business model choices firms make. Since managers experience pluralism and respond to it differently, by doing so they create organizational heterogeneity and possibilities for strategic differentiation. We further draw on business model literature to expand the model, by explaining how different business models, in turn, can lead to different performance outcomes. The conceptual model is tested using survey data of 179 Dutch creative service firms (design agencies, advertisement agencies, audiovisual service providers, and the like). 
  
Commitment to different logics is measured in terms of the firm's score on creative and business orientations, measured by scales derived using Confirmatory Factor Analysis. In order to uncover business model heterogeneity, we use Principal Component Analysis. The firms' scores on orientations, as well as their membership in (the use of) certain business models is calibrated into fuzzy sets. Using fuzzy set Qualitative Comparative Analysis, we explore which configurations of firm orientations and business models lead to superior performance in two domains that correspond to the conflicting logics, and which, on the contrary, are necessary and/or sufficient for below average firm performance. We look at both creative and business performance.   
  
The rest of the paper is structured as follows: we first build the conceptual framework combining the literature on pluralism, institutional complexity and business models. We then formulate hypotheses based on a discussion on strategic conflicts in the creative industries.  Further on, we explain our methods, to then proceed to presenting and discussing our results.  
  
## Literature review
In this section, we synthesize diverse strands of literature to argue why business model heterogeneity in pluralistic settings can be seen as a function of top-manager commitments to the conflicting requirements they are exposed to, and how this heterogeneity can explain performance differentials. We first discuss particularities of success criteria in pluralistic contexts. Then, we conceptualize how differences in commitments to different logics lead to differences in strategic decisions, including decisions about the firm's business model. We then link back the business model heterogeneity to organizational success. Finally, hypotheses are formulated, based on a review of peculiarities of the creative service setting that we study.    
  
### Strategic pluralism and decision-making   
The concept or organizational pluralism is used to describe contexts that are characterized by "multiple objectives, diffuse power and knowledge-based work processes" [@Denis2007, p. 180]. Pluralism arises as a result of "the divergent goals and interests of different groups, each of which have sufficient power bases to ensure that their goals are legitimate to the strategy of the organization" [@Jarzabkowski2006, p. 631]. Pluralism can find its source both within and outside the organization. In hybrid organizations, such as hospitals or universities, competing demands are created by the need to satisfy various stakeholder groups like funding bodies, regulatory institutions, and different client groups [@Denis2007]. In the case of professional service firms (also characteristic to our research setting), the need to retain highly skilled employees often requires managers to act against the market interests, as the profitable work is not always the most interesting one, but the skilled professionals need to be challenged enough to be motivated to perform well [@Teece2003]. 
  
The long-term success and competitive advantage of firms facing conflicting demands depend heavily on their ability to strike a balance in these different domains [@Smith2014]. The pluralism in organizational priorities thus plays an important role in organizing. Most of the literature refers to the pluralism as a property that is pertinent to the higher strategic level of the firm, because it creates tensions concerning the identity and interests of the firm and hence imply divergent strategizing demands. Yet the decisions at the organizational level of the firm are where the pluralism is enacted [@Denis2007; @Jarzabkowski2006]. According to scholars of pluralism and institutional logics, managers experience pluralism and respond to it differently, and by doing so they create organizational heterogeneity and possibilities for strategic differentiation [@Ocasio2016].  
  
### Business model heterogeneity and organizational success in pluralistic settings   
When it comes to strategic differentiation, the topic of business models has become a particularly important one in the last two decades, describing the main mechanisms of value creation and capture of a firm [@Osterwalder2010]. Choosing the right business model has become a crucial source of competitive advantage [@Afuah2004; @Zott2007]. According to the business model perspective, firms outperform each other by converting their strategic goals [@Smith2010] into better-performing configurations of decisions about value propositions, target markets, value creation mechanisms and revenue models [@Baden2013; @Osterwalder2010] than those of their competitors. Nevertheless, the literature has so far been very much focused on the economic value creation [@Massa2017].  As put by @Ocasio2016, "while economic perspectives implicitly argue that business models are driven by market logics [@Teece2010], combinations of other logics such as family, professional, and community may also shape the organization's business model." (p. 292)   
  
The link between business models and different strategic goals has been so far mostly discussed conceptually. One the one hand, authors have argued that strategic complexity and pluralism require such business model that would enable simultaneous agendas to thrive [@Smith2010]. The question is then what business model choices allow to incorporate pluralism in the business model design [@Yunus2010; @Laasch2017]?   
   
On the other hand, scholars have also explored the opposite link, namely, that pluralism is the reason why business models among firms differ and can thus be a positive source of heterogeneity that would allow firms to strategically differentiate themselves through creating competitively superior business models. According to @Ocasio2016, "the greater the degree of field-level pluralism, the greater the heterogeneity in organizational commitments to a subset of logics informing their business models." (p.293) More specifically, we build our empirical framework on the following conclusion of the authors: 
"The complexity of business models - with variations in customer and stakeholder relations, value propositions, activities, and resources shaping organizational commitments - also imply increasing fragmentation in competition within institutional fields. Heterogeneity in business models leads the heterogeneity in sources of value creation across organizations. " (p.294).    
  
Altogether, we expect that a combination of various degrees of commitments to conflicting logics present in a field and different choices of business models will lead to different performance outcomes. 
  
### Conflicts and success criteria in the creative service firms  
The research setting of this study - the creative industries firms [@Caves2000]  -  have a long-lasting tradition of framing the internal and external conflicts between creative and commercial goals as a trade-off, borrowing it from the arts' world.  Yet, creative industries scholars increasingly agree that a clear choice between pursuing creative and commercial activities in the sector is untenable, as it ignores the realities of the most part of creative and cultural production, which actually takes place somewhere in between the two domains [@Hesmondhalgh2006; @Oconnor2010]. This is especially the case in for-profit creative industries, including creative service firms, where the success depends on being good at both creation and commercialization simultaneously [@Jacobs2012]. It would therefore be more realistic to view both creative and business aspects of creative entrepreneurship as necessary [@Ilozor2006]. While pursuing creative and commercial ends simultaneously creates certain tensions, the need to incorporate both considerations in the decision-making can be better framed as an organizational feature that cannot be changed and has to be accepted and managed [@DeFillippi2015; @Lampel2000; @Townley2009].  
  
Despite the acceptance of the fact that both logics are important, the commitments to both are not always equally valued and observed in both theory and practice. At the industry level, theories divide markets into mass (commercial) and niche (artistic) and argue that different kinds of creative production take place in each [@Bourdieu1993]. Consequently, similarly to the work developed on the generic strategies of competitive advantage [@Porter1985], where firms are thought to compete based on either quality or cost efficiency, it is suggested that creative firms should choose between a commercial or creative-artistic strategy, depending on the markets the want to target [@Canavan2013]. At the organizational level, unresolvable conflicts are seen at the level or resource requirements. Creativity requires flexibility, spontaneity, and time, whereas successful commercialization demands control, planning, and efficiency [@Eikhof2006; @Scase2000]. This forces to frame resources in terms of creative and non-creative [@Caves2000]. At the decision-making level, creative firms have been found to consistently prioritize professional standards and creative aspirations over monetary value [@Bos2016; @Jacobs2012], and often struggle with finding a viable business model. We can thus conclude that not all firms are expected to commit to each of the logics in the same way. Based on this premise, we can formulate the following hypotheses: 

**Hypothesis 1:** Different commitments to creative and business logics lead to the implementation of different business models. 

**Hypothesis 2:**  Different configurations of commitment to creative and business logics and business models are sufficient and or necessary for different types of performance. 

## Methods
In order to investigate how commitments to conflicting logics and business models interact to explain performance differentials among creative service firms, we carry out a fuzzy set Qualitative Comparative Analysis (QCA) on the survey data of a sample of 179 Dutch enterprises. We first discuss the general motivation to study business models from a configurational perspective, as well as the premises of QCA. We then describe our sample, measures and analysis step-by-step. 

### A configurational approach to the study of business models  
A growing body of theories and research in the field of organizational studies have tried to depart from previous approaches to studying organizations in terms of bivariate correlations or constrained multivariate relations and suggested that organizations can be best understood as configurations [@Snow2006]. Despite the considerable amount of literature emphasizing holistic, interrelated and configurational nature of business models, it is surprising that there have been only few attempts to apply the conclusions and analytical tools developed in the field of configurational approach to the study of business models. Yet it can be argued that both fields can benefit from each other to address their shortcomings [@Tauscher2017].   

According to @Short2008, firms are better described and understood in terms of resemblance along pre-defined important dimensions that group them in distinct and consistent sets, rather than simply looking at relationships that hold true across all organizations [@Short2008; @Ketchen1993]. This assumption is also the main strength of the approach as it aims to explain and predict organizational success and failure by looking at how firms as configurations perform. The configurational approach relies on the idea that depending on how patterns or attributes are configured, they will lead to different outcomes. This entails causal complexity, equifinality and the belief that the relationships between components are non-linear and not necessarily symmetric [@Fiss2007].   
  
@Snow2006 summarize the application of configurational framework to organization design as follows: 1) it falls under the paradigm of congruence, 2) "organization is conceptualized as a system or configuration whose major components include strategy, people, structure and management processes", 3) performance depends on internal fit between components and external fit with environment, and 4) there is no perfect organization, all configurations have strengths and weaknesses. (p.434).   
  
Configurational approach has been empirically proven in other contexts as a superior alternative for understanding performance differentials. For instance, @Stabell1998 proposed a typology using configurational approach trying to explain different forms of value creation that further would help to understand competitive advantage. @Stavrou2005 discovered strategic human resource management bundles and were able to link them to business performance. Nevertheless, despite the empirical advances, @Snow2006 conclude that up no concepts have been developed that would be holistic enough to live up to the expectation promised by the approach. In this respect, business model concept can be seen as a promising one, for it unites components of all major decision-making groups mentioned by authors and matches the theoretic assumptions that underlie the configurational approach.   
  
For the business model research, configurational approach in return can help to address the lack of tools to deal with the inherently complex, non-linear and equifinal relationship that exists between the elements of each business model but has not been empirically tackled [@Campagnolo2013; @Tauscher2017]. It is often argued that research is rarely accretive and has too little empirical studies; therefore, the exact mechanisms underlying the high-performing configurations have not been properly explained [@Aversa2015]. Studies using configurational approach have developed a set of methodic and analytic tools that facilitate its empirical application. In this respect, QCA has been repeatedly highlighted as a very promising method for organizational configurations [@Campagnolo2013; @Fiss2011; @Tauscher2017]. These tools, as well as research designs used in extant empirical studies on configuration have the potential to considerably advance empirics in the field of business models and have already paved the way to some recent successful applications of QCA in business model literature [@Tauscher2017; @Kulins2016; @Aversa2015].  

### Qualitative Comparative Analysis   
QCA belongs to a family of comparative configurational methods (CCM) that allows for a systematical analysis of comparable cases to identify causally relevant structural conditions (variables) that lead to an identified outcome [@Marx2013; @Thiem2015]. As such, QCA is a case-oriented, as opposed to variable-oriented methods [@Marx2013]. It is equally a set-theoretic method, employing a causes-to-effects approach to examine combinations of causal conditions instead of the more traditional search for linear causation [@Mahoney2006].  
  
QCA thus assists in answering questions that imply configurations, e.g. what factors (X, Z, etc.) combine to cause an outcome (Y)? More precisely it looks at what conditions or combinations of conditions are necessary and/or sufficient for an outcome to occur. Necessary conditions are present whenever we observe an outcome. Sufficient conditions are conditions that display the presence of an outcome whenever the conditions are present. As all configurational methods, also QCA is based on three main assumptions: 1) relationships to outcomes are nonlinear and asymmetric; 2) variables that are causally related in one configuration are not necessarily related in others, implying complex causality; and 3) configurations can be equifinal [@Fiss2011; -@Fiss2007].  
  
When applying QCA in organization studies, variables (also referred to as conditions) are defined in terms of sets of organizational attributes. The choice of conditions can be both theoretical and empirical, namely, based on the knowledge of cases and the setting [@Schneider2013]. A set can be a single condition or a combination of conditions. Each case (firm's response, in our case) is expressed in terms of its membership to the defined sets. For this study, we have chosen to carry out a fuzzy set QCA (fsQCA). In fsQCA cases are not only expressed in their full membership to the sets (1 is in, 0 is out), but also partial memberships can be assigned (partially in, partially out). The process of transforming gathered raw data about cases into membership scores is called calibration [@Thiem2013]. It prescribes the definition of three qualitative thresholds: full membership, the cross-over point, and full non-membership. The crossover point, contrary to most accepted measurement scales, establishes a difference in kind, not degree.   
  
When the data is calibrated into sets, QCA then relies on Boolean algebra to perform systematic cross-case analysis, and using reduction shows combinations that are necessary and or sufficient for the occurrence of an outcome [@Rihoux2009]. Finally, QCA as an approach (rather than only an analytical method) requires the results to be verified by case knowledge and by counterfactual analysis making it explicit what assumptions have been made about logical remainders (i.e. configurations that were not observed, yet are analytically possible) [@Schneider2013].  

### Data and research setting   
In order to gather the data for our study, we conducting a survey among Dutch creative service firms. We chose to focus on creative service firms as a subsector of creative industries for two reasons. Firstly, we wanted to minimize the differences in the variety of external institutional logics and internal drivers the firms could commit to, while still retaining a sample large enough that would span a single sector. Secondly, the choice was made to focus on firms that have a dominant logic in terms of types of goods they produce (in this case, the service logic), so that the business model heterogeneity can be more precisely assessed.   
  
According to Dutch policy documents and industry reports, creative service firms constitute a separate subset of creative industries and refer to firms that carry out the following activities  -  architecture, interior architecture, communication and graphic design, industrial and product design, spatial design, PR agencies, and advertisement agencies.   
  
In order to collect the data, we first approached six professional associations - The Association of Dutch Designers (BNO), The Association of Dutch Architects (BNA), The Association of Dutch Interior Architects (BNI), Dutch Digital Agencies (DDA), The Dutch Game Association (DGA), The Association of Communication (VEA), and asked them to distribute the survey to their members via newsletter and direct emailing, if possible. During the second stage, we obtained a list of enterprises matching the defined sectors of activities from the Dutch Chamber of Commerce and approached them inviting to fill in the survey. 
In order to avoid common method bias, we asked only the founders/ senior managers of the organizations to fill in the survey. As an incentive to respond, the firms were assured of anonymous and offered a personalized report of the results. The total population of firms according approached was approximately 5000. After omitting the incomplete surveys or responses that did not match the criteria, 179 questionnaires were retained, yielding a response rate of 3,6%.  

### Survey measures  
Where possible, we used scaled developed and validate in prior studies. In the cases, where changes, new items, or construct measurements where needed we relied on the general steps suggested for developing measurements in various fields of social sciences [@Churchill1979; @Gerbing1988; @Viswanathan2010; @MacKenzie2011]. We explain this further for each concept separately.  
  
In order to test the validity of the survey, the first versions were extensively discussed with four management scholars and three industry experts. After initial adjustments in items, the questionnaire was presented to two founders of creative service firms asking them to think aloud when filling it in. This led to minor adjustments of wording and to changes in the order of presenting the questions to the respondents. It was then checked again with two scholars and one industry expert. The survey was then pre-tested on founders/managers of 25 firms, using a convenience sample of firms that had taken part of previous qualitative phase.   

#### Commitments to conflicting logics (orientations) 
In order to measure top-management commitment to strategic paradoxes and logics that they are exposed to, we used the organizational identity scale developed by @Voss2006. The scales investigate five values - artistic, achievement, prosocial, customer and financial. We made small modifications in the wording of the items to match the for-profit setting, since the original scales were developed for the non-profit artistic sector. The artistic value dimension was renamed as creative value dimension and an additional dimension of entrepreneurial values adapted from @Srivastava2013 was added. All constructs were measured using a 7-point Likert scale, inviting the respondents to indicate how important the statements are to their firm's identity. The original study treats them as separate constructs, so we first run a Confirmatory Factor Analysis (CFA) specifying a model with 6 different logics that firms can commit to. However, there were several issues. Firstly, the responses on items of the market values scale were highly skewed towards 7, with only 4 respondents answering lower than 6. We removed those items. Secondly, the items of creative, achievement, and social values were highly correlated. Thirdly, the entrepreneurial values scale had very low factor loadings. Therefore, we aggregated the first three concepts under the concept of "Creative Orientation" and retained only the financial values under the concept of "Business Orientation". We specified another model for CFA, and only retained the items with satisfactory loadings. The full list of the original item pool, loadings of the final scales, and various measures of fit can be found in Appendix, Table \@ref(tab:FAor).     
  
#### Performance measures
Consistent with the two general orientations specified in our conceptual framework, we measured two types of performance - business and creative. For business performance, we adapted the professional service firm performance scale developed by @Lander2012. We used the same example in combination with insights from @Voss2006 and our interviews to specify the items for the creative performance construct. We insured that they match the items that were defined in the orientations scales. For each item, we inquired about the respondent's level of satisfaction with firm performance relative to the firm's competitors [@Covin1989], measured using a 7-point Likert scale. In line with @Jarvis2003, we specified a reflective construct. We run a CFA using the specified model, however from eleven creative performance items, we retained only four, and three from the twelve business performance items with satisfactory loadings. The full list of the original item pool, loadings of the final scales, and various measures of fit can be found in Appendix, Table \@ref(tab:FAperfm). 

#### Business models
When attempting to measure business models in empirical studies, two broader approaches have been identified - 1) observing the degree to which business model related decisions follow a certain pattern, e.g. strategy or design theme (e.g. @Zott2007), and 2) treating business models as real attributes that manifest as a set of observable choices (e.g. @Morris2005). We use the latter approach to operationalize the business model concept for our study. In order to develop a measurement scale that would be in line with the conceptualization in terms of "set of choices", we adapted the business model framework developed by @Morris2005 and -@Morris2015. This approach entails deriving taxonomies, as opposed to typologies, and has been argued to be particularly suitable in studies that aim to study business model heterogeneity in specific settings. Similar examples of setting specific operationalizations in terms of component-based choices have proven successful in previous empirical studies in other settings, e.g. in biotechnology [@Bigliardi2005], in carsharing [@Remane2016], in e-business models, in electrical vehicles [@Bohnsack2014] and others. We were also informed by previous scale development efforts in other management fields, particularly operations management (e.g. @Li2006). Likewise, the study of @Clauss2017 on developing measures for business model innovation concept was of particular assistance, as it is closely related to our topic.  
  
Where possible, we used the measures developed by @Morris2005. For the constructs that were measured with items that we judged as too generic for our research purposes, we adapted the items and variables to fit the knowledge intensive (creative) service setting. The modifications were made relying on our substantial knowledge of the field based on earlier qualitative study combined with insights from industry experts and reports and other literature on service firms. The adapted measure of the construct consists of ten dimensions each having two to eight items: knowledge offering in the value proposition, value chain activities in the value proposition, types of offering (product/service), the degree of customization of the offering, differentiation strategy, client segments, resource acquisition strategy, key partners, revenue models, and income sources. All constructs were measured using a 7-point Likert scale, inviting the respondents to indicate how important the aspects are for their firm's business model.   
  
Since we do not expect that business model elements would be correlated, we specified a formative construct [@Jarvis2003]. We also expected that firms could use several types of business models simultaneously [@Markides2004]. Therefore, in order to uncover these types, we run a Principal Component Analysis that tried to find types using the 43 items we specified. The full list of the original item pool, loadings of the final scales, and various measures of fit can be found in Appendix, Table \@ref(tab:PCAbm). Our analysis yielded six components, namely, six types of business models, that were formed by the following items: 
  
**Type 1 : The "classic" creative service firm business model:**  
- Offers mainly services, which are highly customized  
- Value proposition is a combination of several creative sub-disciplines  
- The firms take care of both creative concept development and production and/or implementation part of the projects  
- Compete based on product/service quality  
- Close customer relationships  
- Revenue model based on hourly rates   
- Mainly use income only from own activities  
    
**Type 2 : The revenues diversifying business model:**   
- Licenses, subscriptions, and usage fees  
- Revenue generated from other affiliate firms  
- Investing money in other companies  
- Negative loading on own activities as income source  
- Partners for scaling our business  
- Maintenance and service level agreements  
  
**Type 3 : The outsourcing-based product business model:**  
- Main value chain activities are sales, marketing and distribution   
- Negative loading on the strategy part of the value chain activities    
- Suppliers as the most important partners    
- Revenue model primarily based on product sales  
- Negative loading on the use of hourly rates as a revenue model  
  
**Type 4 : The in-house produced niche product business model:**  
- Offering mainly own products  
- Revenue model based primarily on product sales   
- Acquiring resources in-house  
- Focusing on niche markets  
  
**Type 5 : The external investment business model:**     
- Returns on external investments as main revenue model    
- Significant use of loans as income source  
  
**Type 6 : The co-creating business model:**   
- Complementors as key partners    
- Competitors as key partners  
- Customers as co-creators  
- Partners for scaling our business as key partners  
  
Unsurprisingly, the principal component and the main business model covering the most variance in our data is the traditional business model of knowledge intensive service firms. The other components, i.e. business model types show the possibilities of business model diversification that are currently in use by the sector we study.  
  
### Fuzzy set calibration and Qualitative Comparative Analysis   
Once we had validated the constructs in our survey data, we proceeded to calibrating the raw data for fuzzy set Qualitative Comparative Analysis (fsQCA). Since the original data was gathered using 7-point Likert scales, and hence can be considered as categorical, and not pure interval, we used the total fuzzy and relative method (TRF) suggested by Du??a (2018) to calibrate the data into fuzzy sets.  Table \@ref(tab:setdefinitions) presents the conditions we specified.   
  
Table: (\#tab:setdefinitions) Set definitions.  
  
| Conditions and outcome sets | The case belongs to the set, if... |
|--------------------------------------------------|-------------------------------------------------------------------------------------------------------|
| Creative Orientation (CO) | scores above average high on the selected items of creative, achievement, and social values; |
| Business Orientation (BO) | scores above average high on the selected items of financial value; |
| Business Model 1 (BM1) | has a high score for the component of the traditional creative service firm business model; |
| Business Model 2 (BM2) | has a high score for the component of the revenues diversifying business model; |
| Business Model 3 (BM3) | has a high score for the component of the outsourcing-based product business model; |
| Business Model 4 (BM4) | has a high score for the component of the in-house produced niche product business model; |
| Business Model 5 (BM5) | has a high score for the component of the external investment business model; |
| Business Model 6 (BM6) | has a high score for the component of the co-creating business model; |
| High creative and business performances (BAL) | scores above average high on the selected items of creative and business performance; |
| High business, low creative performance (NOCP) | scores above average high on the selected items of business performance, low on creative performance; |
| High creative, low business performance (NOBP) | scores above average high on the selected items of creative performance, low on business performance; |
| Low creative and business performances (BOTHLOW) | scores above average low on the selected items of creative and business performance; |  
  
After the conditions and outcome sets were calibrated we proceeded to carry out four separate QCAs using the QCA package in R to answer the following questions: 
- Which configurations of orientations and business models are necessary and/or sufficient for having both high creative and business performance?   
- Which configurations of orientations and business models are necessary and/or sufficient for only high creative performance?   
- Which configurations of orientations and business models are necessary and/or sufficient for only high business performance?   
- Which configurations of orientations and business models are necessary and/or sufficient for having both low creative and business performance?   
  
## Results  
We first run analyses of necessity for all four outcomes, testing for the necessity of both absence and presence of our conditions. However, none of the conditions or their absence was individually necessary for any of the outcomes. The results can be found in Tables 4 to 12 of the Appendix.   
  
We then turned to the truth table minimization for testing sufficiency of (combinations of) our conditions. We present the results per each outcome. Following the guidelines of Fiss (2011) and Ragin (2008), we report both core (&#9899;for presence and &#10683; for absence) and peripheral conditions (&#9679;for presence and &#10680; for absence). In our case, the peripheral conditions represent the ones present in the conservative solutions, since no prior empirical, nor theoretical evidence was available to formulate directional expectations. The only exception in our results is the analysis for the presence of both high creative and business performance. After several rounds of analysis, we chose to present the conservative solution, and leave out the parsimonious one. Due to the relatively large number of conditions, and no prior theory for difficult counterfactual analysis, our parsimonious solution has a very high model ambiguity. When allowing the minimization algorithm to search for all possible solutions, it returns 122 possible models that are causally equivalent. Therefore, in the first analysis, we focus on the conservative solution, even though the results are thus only representative of our cases. 

### Analysis 1: High creative, high business performance  
  
All in all, our results confirm the expectations formulated in our hypotheses - diverse combinations of commitments to creative and business logics and business models are equally valid pathways to achieving high performance in both dimensions. There are five configurations where both commitments are present, three where only the creative orientation is present, and absence of the business orientation is an INUS condition, two configurations with the opposite commitments, one where both orientations have to be absent, and two configurations where the orientations are not even causally relevant. We also see that in absolute numbers, most firms are successful (36, configuration 1) when committing to both logics, but not  experimenting with business model innovation (absence of business model conditions 3, 4, 5, and 6).    

The configurations where both orientations are present (1, 5, 6, 7, 8) all exhibit a similar pattern - the combination of both orientations and use of one business model (types one to four), while the absence of other business models is sufficient in order to achieve both high creative and business performance. In the first configuration, instead of the presence of a business model, it is the absence of using Business Model 6 that jointly contributes to success.   
  
There are two configurations where commitment to logics are causally irrelevant (2 and 3). Among these cases, the use of either revenues diversifying business model (BM2) or the in-house produced niche product business model (BM4) in combination with not implementing other business models is sufficient for high performance.     
   
The implications of configurations 10 and 11 seem particularly challenging theoretically - when using the co-creating business model, all other business models must be absent, and only one orientation can guide firms' decisions, the other contributing in its absence. However, both are possible.  

Table: (\#tab: bothhigh) Conservative solution for high creative and high business performance.    
  
| Conditions           | Configurations |      |      |      |      |      |      |      |      |      |      |      |      | 
|----------------------|----------------|------|------|------|------|------|------|------|------|------|------|------|------| 
|                      | 1              | 2    | 3    | 4    | 5    | 6    | 7    | 8    | 9    | 10   | 11   | 12   | 13   | 
| Creative Orientation | &#9679;               |      |      | &#10680;    | &#9679;    | &#9679;     | &#9679;     | &#9679;     | &#10683;   | &#10680;    | &#9679;    | &#9679;    | &#9679;    | 
| Business Orientation | &#9679;              |      |      | &#9899;    | &#9679;    | &#9679;    | &#9679;    | &#9899;    | &#10680;    | &#9679;    | &#10683;    | &#10680;    |      | 
| BM1                  |                | &#10680;    | &#10680;    | &#9899;    | &#10680;    | &#10680;    | &#10680;    | &#9899;    | &#9679;    | &#10680;    | &#10683;    | &#9899;    | &#10680;    | 
| BM2                  |                | &#10680;    | &#9679;    | &#10680;    | &#10680;    | &#10680;    | &#9679;    | &#10680;    | &#10680;    | &#10680;    | &#10683;    | &#10680;    | &#9679;    | 
| BM3                  | &#10680;              | &#10683;    | &#10680;    |      | &#10683;    | &#9679;    | &#10680;    | &#10680;    | &#10683;    | &#10680;    | &#10680;    | &#9899;    | &#10680;    | 
| BM4                  | &#10680;              | &#9899;    | &#10680;    | &#10680;    | &#9899;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    |      | 
| BM5                  | &#10680;              | &#10683;    | &#10680;    | &#10680;    | &#10683;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | 
| BM6                  | &#10680;              | &#10680;    | &#10680;    | &#10680;    |      |      |      |      | &#9899;    | &#9679;    | &#9899;    | &#10680;    | &#10680;    | 
| Consistency          | 0.79           | 0.77 | 0.72 | 0.84 | 0.85 | 0.83 | 0.83 | 0.81 | 0.82 | 0.82 | 0.81 | 0.85 | 0.78 | 
| Raw coverage         | 0.56           | 0.12 | 0.16 | 0.11 | 0.09 | 0.12 | 0.13 | 0.19 | 0.04 | 0.08 | 0.09 | 0.03 | 0.16 | 
| Unique coverage      |                |      |      |      |      |      |      |      |      |      |      |      |      | 
|                      | 0.20           | 0.02 | 0.01 | 0.02 | 0.01 | 0.04 | 0.00 | 0.00 | 0.01 | 0.01 | 0.01 | 0.01 | 0.01 | 
| PRI                  | 0.46           | 0.48 | 0.38 | 0.28 | 0.40 | 0.46 | 0.43 | 0.50 | 0.45 | 0.27 | 0.37 | 0.44 | 0.43 | 
| Nr. cases            | 36             | 10   | 13   | 3    | 4    | 7    | 8    | 10   | 1    | 2    | 2    | 1    | 11   | 
| Solution consistency | 0.73           |      |      |      |      |      |      |      |      |      |      |      |      | 
| Solution coverage    | 0.77           |      |      |      |      |      |      |      |      |      |      |      |      | 
| Solution PRI         | 0.48           |      |      |      |      |      |      |      |      |      |      |      |      | 
| Nr. Cases 1/0/C      | 75/104/0       |      |      |      |      |      |      |      |      |      |      |      |      | 
  
    
Moreover, upon examining the configurations 4, 13, and 12 closer, we can conclude that the traditional business model and creative orientation act as substitutes in combination with either absence or presence of the revenues diversifying business model (BM2). In our analysis, no cases that use both the traditional and the revenue diversifying model simultaneously are represented in the successful solution terms. In fact, our results show that combining business models seems to be challenging in general, if the firms want to achieve high performance in both domains.   
  
There were two configurations that combined two business models successfully, each represented by only one case in our sample. Configuration 9 showed that the presence of the traditional creative service firm business model (BM1) can be successfully combined with the co-creating business model, if all other conditions are absent. Similarly, Configuration 12 shows that the traditional business model can be combined with the outsourcing-based product model (BM3), in the presence of a pronounced creative orientation, but absence of all other conditions.   
  
### Analysis 2: Low creative, high business performance  
For the analysis of firms that exhibit high business performance, but low creative one, there was only one solution term, represented by two cases in our sample, that satisfied our sufficiency criteria. The configuration implies the absence of a creative orientation, presence of the traditional business model combined with the outsourcing-based product business model as core conditions, and the absence of other business models as peripheral conditions.   
  
Table: (\#tab: lowcrhighbus ) Parsimonious solution term for low creative and high business performance.   
  
| Conditions           | Configuration 1 | 
|----------------------|-----------------| 
| Creative Orientation | &#10683;               | 
| Business Orientation |               | 
| BM1                  | &#9899;             | 
| BM2                  | &#10680;             | 
| BM3                  | &#9899;             | 
| BM4                  | &#10680;             | 
| BM5                  | &#10680;             | 
| BM6                  | &#10680;             | 
| Nr. cases            | 2             | 
| Solution consistency | 0.86          | 
| Solution coverage    | 0.04          | 
| Solution PRI         | 0.29          | 
| Nr. Cases 1/0/C      | 2/177/0       |   
  
### Analysis 3: High creative, low business performance  
The solution terms for this outcome are quite surprising, given that four out of six configurations have the business orientation contributing in its presence to the lack of business performance. The most represented configuration (9 cases) is the scenario where a firm has a high business orientation, is implementing the in-house niche product business model, and does not use the co-creating model as the core conditions. The low business performance could be explained by the riskiness of the model, while creative performance due to fact that in-house production is very skill-intensive.  

Table: (\#tab:highcrlowbus ) Solution terms for high creative and low business performance. 
  
| Conditions           | Configurations |      |      |      |      |      | 
|----------------------|----------------|------|------|------|------|------| 
|                      | 1              | 2    | 3    | 4    | 5    | 6    | 
| Creative Orientation | &#9679;              | &#10680;    | &#9679;    | &#9679;    | &#9679;    | &#10680;    | 
| Business Orientation | &#9679;              | &#9899;    | &#9899;    | &#9899;    | &#10683;    | &#10683;    | 
| BM1                  | &#10680;              | &#9899;    | &#9899;    | &#10680;    | &#10683;    | &#9899;    | 
| BM2                  | &#9899;              | &#10680;    | &#10680;    | &#10680;    | &#10683;    | &#10680;    | 
| BM3                  | &#9899;              | &#9899;    | &#10680;    | &#10680;    | &#10680;    | &#10680;    | 
| BM4                  | &#10680;              | &#10680;    | &#10680;    | &#9899;    | &#10683;    | &#10680;    | 
| BM5                  | &#10680;              | &#10680;    | &#10680;    |      | &#10680;    | &#10680;    | 
| BM6                  | &#10680;              | &#10680;    | &#9899;    | &#10683;    | &#9899;    | &#9899;    | 
| Consistency          | 0.67           | 0.85 | 0.77 | 0.76 | 0.79 | 0.82 | 
| Raw coverage         | 0.03           | 0.04 | 0.06 | 0.19 | 0.17 | 0.05 | 
|                      |                |      |      |      |      |      | 
| Unique coverage      |                |      |      |      |      |      | 
|                      | 0.00           | 0.02 | 0.01 | 0.17 | 0.01 | 0.00 | 
| PRI                  | 0.24           | 0.28 | 0.27 | 0.39 | 0.26 | 0.27 | 
| Nr. cases            | 1              | 1    | 1    | 9    | 1    | 1    | 
| Solution consistency | 0.73           |      |      |      |      |      | 
| Solution coverage    | 0.35           |      |      |      |      |      | 
| Solution PRI         | 0.32           |      |      |      |      |      | 
| Nr. Cases 1/0/C      | 14/165/0       |      |      |      |      |      |   

  
The more expected scenario is represented by configuration 5, where the business orientation is absent, along with all the other business models, except for the co-creating one, which is a core condition. According Configuration 1, combining Business Model 2 and Business model 3 while committing to both logics, is good for creative performance, but not for business performance. If both orientations are absent, the combination of Business Models 1 and 6, can still lead to high creative performance, but are not good for the business. 
  
Configuration 2, similarly to the solution of high business performance, uses a combination of Business Model 1 and Business Model 3, and in both solutions creative orientation is absent. However, interestingly, the presence of business orientation and absence of other business models, makes this combination creatively successful. 
  
### Analysis 4: Low creative, low business performance
The analysis on low performing firms in both dimensions yielded three solutions. The first is a combination of the absence of creative orientation, the use of traditional business model, the absence of other business models, A similar solution where the business orientation was contributing to the outcome in its presence made the difference in Analysis 1 and ensured that the firms perform well both creatively and commercially. The second and third configurations show the absence of business orientation as a core condition, and the presence of creative orientation as a peripheral one, both having the absence of the traditional business model as a peripheral condition as well. One configuration implies combining the co-creating business model with the revenue diversifying business model. The other combination prescribes the implementation of the external investment model along with the in-house niche product business model. 
  
Table: (\#tab: highcrlowbus ) Parsimonious solution term for low creative and low business performance. 
  
| Conditions           | Configurations |      |      | 
|----------------------|----------------|------|------| 
|                      | 1              | 2    | 3    | 
| Creative Orientation | &#10683;              | &#9679;    | &#9679;    | 
| Business Orientation |                | &#10683;    | &#10683;    | 
| BM1                  | &#9899;              | &#10680;    | &#10680;    | 
| BM2                  | &#10683;              | &#9899;    | &#10680;    | 
| BM3                  | &#10683;              | &#10680;    | &#10680;    | 
| BM4                  | &#10680;              | &#10680;    | &#9679;    | 
| BM5                  | &#10680;              | &#10680;    | &#9899;    | 
| BM6                  | &#10683;              | &#9899;    | &#10680;    | 
| Consistency          | 0.74           | 0.85 | 0.83 | 
| Raw coverage         | 0.15           | 0.02 | 0.01 | 
| Unique coverage      |                |      |      | 
|                      | 0.14           | 0.02 | 0.01 | 
| PRI                  | 0.224          | 0.35 | 0.71 | 
| Nr. cases            | 5              | 1    | 1    | 
| Solution consistency | 0.75           |      |      | 
| Solution coverage    | 0.18           |      |      | 
| Solution PRI         | 0.30           |      |      | 
| Nr. Cases 1/0/C      | 7/172/0        |      |      |   
  
  
## Discussion  
Our results confirm our hypotheses, as well as the general conceptual propositions put forward by Ocasio and Radoynovska (2016): diverse commitments to competing logics lead to business model heterogeneity, and in turn impact the way firms perform. There are several important points to make based on our results. 
  
Firstly, the interaction between logics and business models show a high degree of complexity. Contrary to the general expectation that significant commitments to both logics are needed in order to perform well in both domains, our results show that commitments to both creative and business logic work well in combination with certain business models, but not with others. Analysis one showed, that the firms that exhibit both orientations are successful in both domains only if they implement a single business model and not others. 
  
Secondly, there are configurations that prove that it is enough to commit more to one logic, if other things are present. Creative orientation works with the revenue diversifying business model (BM2), while business orientation, in the absence of creative orientation works with either the traditional business model, or the co-creating business model (BM6). This could be explained by the fact that business model types can have a certain commitment to a certain logic by their very nature, similarly to what Amit and Zott (2007) have coined as the design-theme - business models that help to reach certain strategic objectives. For instance, the traditional business model is in itself slightly "creative", and so is the co-creating business model, meaning that a business orientation can only help to commit to both equally. The opposite goes for the revenue diversifying business model, which is much more business oriented, whereby the creative orientation helps to counter-balance the commitments to the other side. 
  
In addition, while some commitment combinations match with certain business models, they are "difficult" with others. For instance, the same combination of high creative orientation and absence of business orientation led to firms performing well in both domains in the cases just discussed but failed to lead to high performance if combined with business models 3 and 6, or 4 and 5 (Analysis 4, Configurations 2 and 3).   
  
Thirdly, when comparing some configurations across our analyses, we can see that commitments to logics change the performance of the same business models. For instance, the implementation of the traditional business model in the absence of other business models leads to low performance in both domains, if combined with the absence of creative orientation. However, when combined with only the business orientation, or both orientations, it contributes to being good at both creative and business aspects of the firm's activities.   
  
Fourthly, we also saw some configurations where commitments to logics are simply causally irrelevant. The configurations 2 and 3 of Analysis 1 prescribed that implementation of either the revenue diversifying business model (BM2) or the in-house niche product business model (BM4), given that all other business models are absent, was enough to perform high. 
  
Fifthly, the most challenging finding result from the Analysis 3.  In half of the sufficient configurations, the business orientation was present, it is therefore unexpected that the firms would score high on creative performance, but low on the business one. However, in those combinations the firms were also combining two business models, and mostly the more creativity- oriented ones. Hence, we can conclude that too much creative experimentation with business models for the sake of business performance leads to the opposite outcome.  

Finally, this leads us to the one of the most interesting topics, namely, the implementation of multiple business models. Contrary to the much of recent literature, having multiple business models (Snihkur & Tarzijan, 2017) at the same time is difficult, for achieving conflicting performance goals simultaneously (Markides & Charitou, 2004). From a configurational perspective, one could expect that the other business models just are not causally relevant, when a particular business model is implemented. However, our results clearly show that the absence of other business models except for the one contributing to the outcome was a combined INUS union in almost all configurations in Analysis 1. There were only two configurations (9 and 12) that implied the use of two business models in a successful configuration, each represented by a single case. We can hence conclude that the higher the degree of strategic complexity that firms have to face, the more difficult it is to implement two or more business models simultaneously.   

## Conclusions  
Base on the propositions put forward by Ocasio and Radoynovska (2016), we posited that firms that face competing logics commit to them differently, thereby creating business model heterogeneity, which in turn can explain performance differentials. We carried out a fuzzy set Qualitative Comparative Analysis to uncover the combinations of commitments to business and creative logics and business models that are necessary and/or sufficient for performing well both creatively and business-wise.      
  
Our results contribute to several strands of literature. For the business model literature, our article proposes a typology of business models in knowledge-intensive service firms. This typology highlights the business model related decisions that are defining the differences between types. For the literature on organizational pluralism, it shows the business model related mechanisms that are needed, if firms are committing (either by choice or necessity) to several logics simultaneously, as opposed to focusing on one. We also contribute to the creative industries literature by showing how firms can balance between creativity and commercial interests by using business models. Finally, and most importantly, this paper shows the added value of applying the configurational approach to the study of organizations, and the combined study of business models and firm strategies in particular. Methodically we demonstrate how factor analysis and principal component analysis can be combined successfully with Qualitative Comparative Analysis.   

## Appendix  

Table: (\#tab: FAor) Original items for values/orientations scales and results of confirmatory factor analysis.   
  
| Items (original pool)                                                                               | Loadings Creative Orientation | Loadings Business Orientation |      | 
|-----------------------------------------------------------------------------------------------------|-------------------------------|-------------------------------|------| 
| Encourage employees to challenge the boundaries of our field (VC_1)                                 |                               |                               |      | 
| Produce very innovative goods and services (VC_2)                                                   | 0.61                          |                               |      | 
| Work on creative and/or challenging projects (VC_3)                                                 | 0.53                          |                               |      | 
| Deliver goods or services that are publicly recognized for their excellence (VA_1)                  |                               |                               |      | 
| Receive awards for our work (VA_2)                                                                  |                               |                               |      | 
| Deliver goods or services recognized for their contribution to the field (VA_3)                     |                               |                               |      | 
| Offer new perspectives and knowledge to the society (VS_1)                                          | 0.88                          |                               |      | 
| Contribute to solving societal challenges (VS_2)                                                    | 0.72                          |                               |      | 
| Be a "good" company (VS_3)                                                                          |                               |                               |      | 
| Expand turnover (VF_1)                                                                              |                               |                               | 0.60 | 
| Secure future profitability (VF_2)                                                                  |                               | 0.72                          |      | 
| Work on projects that bring in money (VF_3)                                                         |                               |                               |      | 
| Grow in terms of size (VF_4)                                                                        |                               | 0.54                          |      | 
| Commit to customer satisfaction (VM_1)                                                              |                               |                               |      | 
| Provide good value for our customers (VM_2)                                                         |                               |                               |      | 
| Take customer expectations into account (VM_3)                                                      |                               |                               |      | 
| Ensure that our unique advantages can withstand the changes in the industry (VE_1)                  |                               |                               |      | 
| Pro-actively face the challenges brought by technological development for us and our clients (VE_2) |                               |                               |      | 
| Take entrepreneurial risks to prepare for the changes brought by the market (VE_3)                  |                               |                               |      | 
| Cronbach alpha new scale                                                                            | 0.783                         | 0.644                         |      | 
| Average Variance Extracted                                                                          | 0.505                         | 0.387                         |      | 
| Chi-Square                                                                                          | 0.093                         |                               |      | 
| RMSEA                                                                                               | 0.055                         |                               |      | 
| SRMR                                                                                                | 0.058                         |                               |      | 
| CFI                                                                                                 | 0.974                         |                               |      | 
  
  
Table: (\#tab: FAperf) Original items for performance scales and results of confirmatory factor analysis.  
  
| Items (original pool) | Business performance | Creative performance |
|-----------------------------------------------------------------------------------------|----------------------|----------------------|
| Gross profits per partner. (BP_1) | 0.729 |  |
| Competitive hourly fee. (BP_2) |  |  |
| Gross margin on provided services. (BP_3) | 0.730 |  |
| Competitive cost structure. (BP_4) |  |  |
| Overhead percentage. (BP_5) |  |  |
| Retention of the largest clients. (BP_6) |  |  |
| Implementing new business models. (BP_7) |  |  |
| Retention of clients. (BP_8) |  |  |
| Attracting new clients. (BP_9) |  |  |
| Growth in profits. (BP_10) |  | 0.810 |
| Growth in staff. (BP_11) |  |  |
| Efficient firm organization. (BP_12) |  |  |
| Producing highly innovative work. (CP_1) |  | 0.749 |
| Working on projects that challenge the boundaries of the field. (CP_2) |  | 0.787 |
| Attracting the best creative professionals. (CP_3) |  |  |
| Reputation on the labor market. (CP_4) |  |  |
| Reputation among peers. (CP_5) |  |  |
| Receiving good critic's reviews for its work. (CP_6) |  |  |
| Receiving industry awards for its work. (CP_7) |  |  |
| Delivering work that is relevant for the society. (CP_8) |  |  |
| Working on projects that match the firm's creative and professional aspirations. (CP_9) |  | 0.734 |
| Creating the desired impact with its work. (CP_10) |  | 0.679 |
| Keeping the employees challenged and satisfied. (CP_11) |  |  |
| Cronbach's alpha | 0.798 | 0.824 |
| AVE | 0.577 | 0.552 |
| Chi-Square | 0.006 |  |
| RMSEA | 0.084 |  |
| SRMR | 0.045 |  |
| CFI | 0.964 |  |  

Table: (\#tab: PCAbm) Business model item pool, loadings of Principal Component analysis.   
  
| Q2 Our firm offers services based on knowledge and expertise in...                                                         | PC1   | PC2   | PC3   | PC4   | PC5   | PC6   | 
|----------------------------------------------------------------------------------------------------------------------------|-------|-------|-------|-------|-------|-------| 
| A specific creative sub-discipline (for instance, graphic design, audiovisual services) (BM1_1)                            |       |       |       |       |       |       | 
| A combination of several creative sub-disciplines (an all-around creative agency) (BM1_2)                                  | 0.50  |       |       |       |       |       | 
| A combination of creative and non-creative disciplines (e.g. data analysis, manufacturing) (BM1_3)                         |       | 0.35  |       |       |       |       | 
| Q3 We offer services that include...                                                                                       |       |       |       |       |       |       | 
| Research and strategy (BM2_1)                                                                                              |       | 0.39  | -0.50 |       |       |       | 
| Creative concept development (BM2_2)                                                                                       | 0.59  |       |       |       |       |       | 
| Production and/or implementation (BM2_3)                                                                                   | 0.54  |       |       |       |       |       | 
| Sales, marketing and/or distribution (BM2_4)                                                                               |       |       | 0.51  |       |       |       | 
| Q4 We offer...                                                                                                             |       |       |       |       |       |       | 
| Own products (BM3_1)                                                                                                       |       |       |       | 0.51  |       |       | 
| Services (BM3_2)                                                                                                           | 0.63  |       |       |       |       |       | 
| Service platforms (bringing several parties together) (BM3_3)                                                              |       |       |       |       |       |       | 
| Products/ services of others (BM3_4)                                                                                       |       |       |       |       |       |       | 
| Q5 Our service offering consists of...                                                                                     |       |       |       |       |       |       | 
| Highly customized services and products (BM4_1)                                                                            | 0.66  |       |       |       |       |       | 
| Modular services and products (can be broken down into smaller components, offered separately, mixed and matched) (BM4_2)  |       |       |       |       |       |       | 
| Maintenance and service-level agreements (BM4_3)                                                                           |       | 0.56  |       |       |       |       | 
| Q6 We differentiate ourselves from our competitors with...                                                                 |       |       |       |       |       |       | 
| Image of operational excellence (BM5_1)                                                                                    |       |       |       |       |       |       | 
| Product and/ or service quality (BM5_2)                                                                                    | 0.62  |       |       |       |       |       | 
| Leadership in innovation and/or creativity (BM5_3)                                                                         |       |       |       |       |       |       | 
| Low cost/ efficiency (BM5_4)                                                                                               |       |       |       |       |       |       | 
| Close customer relationships (BM5_5)                                                                                       | 0.55  |       |       |       |       |       | 
| Q8 We create value for...                                                                                                  |       |       |       |       |       |       | 
| Niche markets (applying our expertise in particular client sectors, segments)  (BM7_1)                                     |       |       |       | 0.40  |       |       | 
| General markets with no specific specialization (BM7_2)                                                                    |       |       |       |       |       |       | 
| Business-to-business (BM7_3)                                                                                               | 0.55  |       |       |       |       |       | 
| Business-to-consumer (BM7_4)                                                                                               |       |       |       |       |       |       | 
| Business-to-government (BM7_5)                                                                                             |       |       |       |       |       |       | 
| Q9 In order to deliver our services / products...                                                                          |       |       |       |       |       |       | 
| We acquire and develop the resources needed in-house (BM8_1)                                                               |       |       |       | 0.45  |       |       | 
| We outsource the resources that are needed to external parties (BM8_2)                                                     |       |       |       |       |       |       | 
| Q10 The key partners needed in order to create our offering are...                                                         |       |       |       |       |       |       | 
| Suppliers (BM9_1)                                                                                                          |       |       | 0.52  |       |       |       | 
| Complementors (companies that sell products or services that complement ours, e.g. front-end development) (BM9_2)          |       |       |       |       |       | 0.43  | 
| Competitors (BM9_3)                                                                                                        |       |       |       |       |       | 0.42  | 
| Customers as co-creators (BM9_4)                                                                                           |       |       |       |       |       | 0.42  | 
| Partners for scaling our business (BM9_5)                                                                                  |       | 0.55  |       |       |       | 0.42  | 
| Q11 The following arrangements are an important part of our revenue model ...                                              |       |       |       |       |       |       | 
| Hourly rates (BM10_1)                                                                                                      | 0.50  |       | -0.50 |       |       |       | 
| Royalties (BM10_2)                                                                                                         |       |       |       |       |       |       | 
| Product sales (BM10_3)                                                                                                     |       |       | 0.55  | 0.43  |       |       | 
| Licenses, subscriptions and usage fees (BM10_4)                                                                            |       | 0.60  |       |       |       |       | 
| Mark up (margins on reselling or fee for mediating transactions between parties) (BM10_5)                                  |       |       |       |       |       |       | 
| No cure, no pay (BM10_7)                                                                                                   |       |       |       |       |       |       | 
| Investing our time or money in other enterprises (BM10_9)                                                                  |       | 0.50  |       |       |       |       | 
| Q12 The income needed to operate our business comes from...                                                                |       |       |       |       |       |       | 
| Revenue generated by our own activities (BM11_1)                                                                           | 0.54  | -0.50 |       |       |       |       | 
| Revenue from other spinout and/or affiliate firms (BM11_2)                                                                 |       | 0.50  |       |       |       |       | 
| Subsidies and grants (BM11_3)                                                                                              |       |       |       |       |       |       | 
| Loans (BM11_4)                                                                                                             |       |       |       |       | 0.96  |       | 
| Returns on external investments (BM11_5)                                                                                   |       |       |       |       | 0.95  |       | 
| Eigenvalue                                                                                                                 | 5.66  | 4.04  | 2.89  | 2.56  | 2.01  | 1.68  | 
| Percentage of variance explained                                                                                           | 13.18 | 9.39  | 6.73  | 5.96  | 4.89  | 3.90  | 
| Cumulative percentage of variance explained                                                                                | 13.18 | 22.57 | 29.30 | 35.25 | 40.15 | 44.06 |   
    

## References    
  
<div id="refs"></div>   